FROM golang:1.20 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/bin/orders .
CMD ["./orders"]
