version: "3.1"

services:
  mongo_auth:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: auth
      ME_CONFIG_MONGODB_SERVER: mongo_auth
    ports:
      - 27017:27017
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  mongo_tickets:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: tickets
      ME_CONFIG_MONGODB_SERVER: mongo_tickets
    ports:
      - 27018:27017
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  mongo_orders:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: orders
      ME_CONFIG_MONGODB_SERVER: mongo_orders
    ports:
      - 27019:27017
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  mongo_payments:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: payments
      ME_CONFIG_MONGODB_SERVER: mongo_payments
    ports:
      - 27020:27017
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  nats:
    container_name: nats
    image: nats-streaming:latest
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-hbi"
      - "5s"
      - "-hbt"
      - "5s"
      - "-hbf"
      - "2"
      - "-SD"
      - "-DV"
      - "-cid"
      - "ticketing"
      - "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
